app = "deluxnet-mobile-mahegots"
primary_region = "dfw"

[build]
  dockerfile = "apps/mobile/Dockerfile"
  [build.args]
    EXPO_PUBLIC_API_URL = "https://deluxnet-api-mahegots.fly.dev/api/v1"

[http_service]
  internal_port = 80
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
